"""add_dob_delete_request_cancel_comment

Revision ID: 21b8738acdcb
Revises: b006b4319e28
Create Date: 2026-03-16 12:20:44.502569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21b8738acdcb'
down_revision: Union[str, Sequence[str], None] = 'b006b4319e28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leave_requests', sa.Column('cancel_comment', sa.Text(), nullable=True))
    op.add_column('sevaks', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('sevaks', sa.Column('delete_requested', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('sevaks', sa.Column('delete_requested_by', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sevaks', 'delete_requested_by')
    op.drop_column('sevaks', 'delete_requested')
    op.drop_column('sevaks', 'date_of_birth')
    op.drop_column('leave_requests', 'cancel_comment')
    # ### end Alembic commands ###
