"""added default_week_off

Revision ID: b006b4319e28
Revises: 25cd769b3a39
Create Date: 2026-03-11 15:29:22.401534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b006b4319e28'
down_revision: Union[str, Sequence[str], None] = '25cd769b3a39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sevaks', sa.Column('default_week_off', sa.String(length=20), server_default='Sunday', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sevaks', 'default_week_off')
    # ### end Alembic commands ###
